blank_issues_enabled: true
contact_links:
  - name: General Discussion
    url: https://github.com/jeremedia/ok-offline/discussions
    about: For questions, ideas, and general discussion about OK-OFFLINE